# Packages

# Standard library
import json
from pathlib import Path

# Third-party
import pandas as pd
import requests

# Local
import unsafe.files as unfile

"""
Define our utils
"""

def get_dir(str_tokens, endpoint, download_root, api_ext):
    """
    Construct the output path for a downloaded file.

    Parameters
    ----------
    str_tokens
        Tokens describing the download entry. These are generated by
        splitting the download name (e.g., "STATEABBR_url_ref_tract").

    endpoint
        Download URL or API endpoint.

    download_root
        Root directory for downloaded files.

    api_ext
        Dictionary mapping API download names to file extensions.

    Returns
    -------
    Path
        Output path for the downloaded file.
    """
    # First token determines the wildcard directory
    wcard_name = "{" + str_tokens[0] + "}"

    # Second token identifies whether this is a URL or API download
    end_type = str_tokens[1]

    # Final token is the base filename
    file_pre = str_tokens[-1]

    # Intermediate tokens define the directory structure
    mid_dirs = Path(*str_tokens[2:-1])

    if end_type == "api":
        filename = file_pre + api_ext[file_pre]
    else:
        filename = file_pre + "." + endpoint.split(".")[-1]

    return (
        Path(download_root)
        / mid_dirs
        / wcard_name
        / filename
    )


def process_file(file):
    """
    Process a row of the download dataframe.

    Parameters
    ----------
    file
        Row from the download dataframe produced by
        ``DataFrame.itertuples()``.

    Returns
    -------
    tuple[list[str], str]
        Download name tokens and the corresponding endpoint.
    """

    name = file[0]
    endpoint = file[1]

    return name.split("_"), endpoint


def download_url(url, save_path, chunk_size=128):
    """
    Download a file from a URL.

    Parameters
    ----------
    url
        Download URL.

    save_path
        Output file path.

    chunk_size
        Streaming chunk size in bytes.
    """

    save_path = Path(save_path)

    r = requests.get(url, stream=True)

    with save_path.open("wb") as fd:
        for chunk in r.iter_content(chunk_size=chunk_size):
            fd.write(chunk)


def download_api(url, save_path):
    """
    Download JSON data from an API endpoint.

    Parameters
    ----------
    url
        API endpoint.

    save_path
        Output file path.
    """

    save_path = Path(save_path)

    data = requests.get(url).json()

    with save_path.open("w") as fd:
        json.dump(data, fd)

def process_download_config(config):
    """
    Convert the download section of a configuration dictionary into
    a dataframe suitable for download_raw().
    """

    return pd.json_normalize(
        config["download"],
        sep="_",
    ).T

def download_raw(
    files,
    wcard_dict,
    download_root,
    api_ext,
):
    """
    Download a collection of files defined by the download configuration.

    Parameters
    ----------
    files
        Subset of the processed download dataframe.

    wcard_dict
        Dictionary mapping wildcard placeholders (e.g., ``{FIPS}``) to
        replacement values.

    download_root
        Root directory where downloaded files will be written.

    api_ext
        Dictionary mapping API download names to file extensions.
    """

    for file in files.itertuples():

        # Get the download name tokens and endpoint
        str_tokens, endpoint = process_file(file)

        # Determine the output filepath and replace wildcard placeholders
        out_filepath = get_dir(
            str_tokens,
            endpoint,
            download_root,
            api_ext,
        )
        out_filepath = unfile.fill_wcard(out_filepath, wcard_dict)
        endpoint = unfile.fill_wcard(endpoint, wcard_dict)

        # Prepare the output directory
        unfile.prepare_saving(out_filepath)

        # Download the file
        if str_tokens[1] == "api":
            download_api(endpoint, out_filepath)
        else:
            download_url(endpoint, out_filepath)

        print(f"Downloaded: {out_filepath.name}")
